rke2_required_packages:
  - open-iscsi
  - nfs-common
  - curl

rke2_kernel_modules:
  - overlay
  - br_netfilter

rke2_sysctl:
  net.bridge.bridge-nf-call-iptables: "1"
  net.bridge.bridge-nf-call-ip6tables: "1"
  net.ipv4.ip_forward: "1"
