apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: freshcloud-ui
  namespace: freshcloud-ui
spec:
  tls:
    - hosts:
        - ui-dev.freshcloud.local
      secretName: freshcloud-ui-dev-tls
  rules:
    - host: ui-dev.freshcloud.local
