apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: ingress-host.yaml
images:
  - name: ghcr.io/freshcloud/freshcloud-ui
    newName: ghcr.io/freshcloud/freshcloud-ui
    newTag: 0.1.0
