all:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/freshcloud_id_ed25519
    bastion_host: REPLACE_ME_STAGE_BASTION_PUBLIC_IP
    ansible_ssh_common_args: "-o ProxyJump=ubuntu@{{ bastion_host }}"
  children:
    access:
      hosts: {}
    edge:
      hosts: {}
    k8s:
      hosts: {}
