apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces/apps.yaml
  - security/default-deny-networkpolicy.yaml
  - security/allow-dns-egress.yaml
  - security/rbac-readonly-viewer.yaml
