all:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/freshcloud_id_ed25519
    bastion_host: 198.51.100.10
    ansible_ssh_common_args: "-o ProxyJump=ubuntu@{{ bastion_host }}"
  children:
    access:
      hosts:
        fc-mvp-euw1-access-01:
          ansible_host: 198.51.100.10
          private_ip: 10.40.0.30
          ansible_ssh_common_args: ""
    edge:
      hosts:
        fc-mvp-euw1-edge-01:
          ansible_host: 198.51.100.11
          private_ip: 10.40.0.20
        fc-mvp-euw1-edge-02:
          ansible_host: 198.51.100.12
          private_ip: 10.40.0.21
    k8s:
      hosts:
        fc-mvp-euw1-k8s-01:
          ansible_host: 10.40.0.10
          private_ip: 10.40.0.10
        fc-mvp-euw1-k8s-02:
          ansible_host: 10.40.0.11
          private_ip: 10.40.0.11
        fc-mvp-euw1-k8s-03:
          ansible_host: 10.40.0.12
          private_ip: 10.40.0.12
