apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - app-kube-prometheus-stack.yaml
  - app-loki.yaml
  - app-promtail.yaml
  - grafana-dashboard-platform-overview.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: freshcloud-observability
