apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../apps/cert-manager/base
  - ../../apps/ingress-nginx/base
  - ../../apps/external-secrets/base
patches:
  - path: patches/cert-manager.yaml
  - path: patches/ingress-nginx.yaml
  - path: patches/external-secrets.yaml
